name: YAPE - Java CI With Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile Gradle
      run: gradle build -x test
    
    - name: Run tests
      run: gradle clean test --tests "co.com.wompi.runners.*" aggregate -i
      env:
        AUTH_KEY: ${{ secrets.AUTH_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Archive Serenity reports
      uses: actions/upload-artifact@v3
      with:
        name: serenity-reports
        path: target/site/serenity
